version: '3.1'

services:

  iroha-node:
    image: soramitsu/iroha:1.4.0-patch-2
    ports:
      - 10001:10001
      - 50051:50051
      - 7001:7001
      - 50508:50508
    environment:
      - "KEY=node1"
    volumes:
      - ./iroha/blockstore:/tmp/rdb
      - ./iroha/config:/opt/iroha_data
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "20"
    restart: always